## import libraries

In [6]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB

### prepare data


In [14]:
df_train = pd.read_csv("data/fp/fp_train.csv", delimiter=',', header=None, names=[i for i in range(2001)], index_col=False)

In [15]:
df_test = pd.read_csv("data/fp/fp_train.csv", delimiter=',', header=None, names=[i for i in range(2001)], index_col=False)

### exploratory

In [16]:
df_train.head(10)

0     1     2     3     4     5     6     7     8     9     ...   1991  \
0     0     0     0     1     0     1     0     0     0     0  ...      0   
1     0     0     1     1     0     1     0     0     0     2  ...      0   
2     3     1     0     0     0     1     0     0     0     0  ...      0   
3     0     2     1     0     0     0     0     1     0     0  ...      0   
4     0     0     0     0     0     0     0     0     0     3  ...      0   
5     0     0     0     0     0     0     0     0     0     0  ...      0   
6     0     0     0     1     0     1     0     0     0     0  ...      0   
7     0     0     0     0     0     0     2     0     0     2  ...      0   
8     0     1     0     0     0     1     0     0     0     0  ...      0   
9     0     0     0     0     0     1     0     0     0     0  ...      0   

   1992  1993  1994  1995  1996  1997  1998  1999  2000  
0     0     0     0     2     0     0     2     1     4  
1     0     2     0     0     0     0     0     0     7  
2     0     0     0     0     0     0     1     0    12  
3     0     0     3     0     0     0     0     0     5  
4     1     0     0     0     1     1     1     0     5  
5     0     0     0     0     0     0     0     0     9  
6     0     0     0     0     0     0     0     2     4  
7     0     0     0     0     0     1     1     0     1  
8     0     0     0     0     0     0     0     1    15  
9     0     0     0     0     0     0     0     0     8  

[10 rows x 2001 columns]

In [17]:
df_test.head(10)

0     1     2     3     4     5     6     7     8     9     ...   1991  \
0     0     0     0     1     0     1     0     0     0     0  ...      0   
1     0     0     1     1     0     1     0     0     0     2  ...      0   
2     3     1     0     0     0     1     0     0     0     0  ...      0   
3     0     2     1     0     0     0     0     1     0     0  ...      0   
4     0     0     0     0     0     0     0     0     0     3  ...      0   
5     0     0     0     0     0     0     0     0     0     0  ...      0   
6     0     0     0     1     0     1     0     0     0     0  ...      0   
7     0     0     0     0     0     0     2     0     0     2  ...      0   
8     0     1     0     0     0     1     0     0     0     0  ...      0   
9     0     0     0     0     0     1     0     0     0     0  ...      0   

   1992  1993  1994  1995  1996  1997  1998  1999  2000  
0     0     0     0     2     0     0     2     1     4  
1     0     2     0     0     0     0     0     0     7  
2     0     0     0     0     0     0     1     0    12  
3     0     0     3     0     0     0     0     0     5  
4     1     0     0     0     1     1     1     0     5  
5     0     0     0     0     0     0     0     0     9  
6     0     0     0     0     0     0     0     2     4  
7     0     0     0     0     0     1     1     0     1  
8     0     0     0     0     0     0     0     1    15  
9     0     0     0     0     0     0     0     0     8  

[10 rows x 2001 columns]

### get features

In [18]:
x_train = df_train.iloc[:,:-1]
x_train.head(5)

0     1     2     3     4     5     6     7     8     9     ...   1990  \
0     0     0     0     1     0     1     0     0     0     0  ...      2   
1     0     0     1     1     0     1     0     0     0     2  ...      0   
2     3     1     0     0     0     1     0     0     0     0  ...      0   
3     0     2     1     0     0     0     0     1     0     0  ...      0   
4     0     0     0     0     0     0     0     0     0     3  ...      0   

   1991  1992  1993  1994  1995  1996  1997  1998  1999  
0     0     0     0     0     2     0     0     2     1  
1     0     0     2     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     1     0  
3     0     0     0     3     0     0     0     0     0  
4     0     1     0     0     0     1     1     1     0  

[5 rows x 2000 columns]

In [19]:
x_test = df_test.iloc[:,:-1]
x_test.head(5)

0     1     2     3     4     5     6     7     8     9     ...   1990  \
0     0     0     0     1     0     1     0     0     0     0  ...      2   
1     0     0     1     1     0     1     0     0     0     2  ...      0   
2     3     1     0     0     0     1     0     0     0     0  ...      0   
3     0     2     1     0     0     0     0     1     0     0  ...      0   
4     0     0     0     0     0     0     0     0     0     3  ...      0   

   1991  1992  1993  1994  1995  1996  1997  1998  1999  
0     0     0     0     0     2     0     0     2     1  
1     0     0     2     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     1     0  
3     0     0     0     3     0     0     0     0     0  
4     0     1     0     0     0     1     1     1     0  

[5 rows x 2000 columns]

### get labels

In [20]:
y_train = df_train.iloc[:,-1:]
y_train.head(5)

2000
0     4
1     7
2    12
3     5
4     5

In [21]:
y_test = df_test.iloc[:,-1:]
y_test.head(5)

2000
0     4
1     7
2    12
3     5
4     5

### data normalization

In [22]:
x_train = (x_train-x_train.min())/(x_train.max()-x_train.min())
x_train.head(5)

0     1         2         3     4     5     6     7     8     9     ...   \
0  0.00   0.0  0.000000  0.166667   0.0   0.5   0.0  0.00   0.0  0.00  ...    
1  0.00   0.0  0.333333  0.166667   0.0   0.5   0.0  0.00   0.0  0.50  ...    
2  0.75   0.2  0.000000  0.000000   0.0   0.5   0.0  0.00   0.0  0.00  ...    
3  0.00   0.4  0.333333  0.000000   0.0   0.0   0.0  0.25   0.0  0.00  ...    
4  0.00   0.0  0.000000  0.000000   0.0   0.0   0.0  0.00   0.0  0.75  ...    

   1990  1991      1992      1993  1994  1995  1996      1997      1998  1999  
0   0.5   0.0  0.000000  0.000000  0.00   0.4  0.00  0.000000  0.666667  0.25  
1   0.0   0.0  0.000000  0.333333  0.00   0.0  0.00  0.000000  0.000000  0.00  
2   0.0   0.0  0.000000  0.000000  0.00   0.0  0.00  0.000000  0.333333  0.00  
3   0.0   0.0  0.000000  0.000000  0.75   0.0  0.00  0.000000  0.000000  0.00  
4   0.0   0.0  0.333333  0.000000  0.00   0.0  0.25  0.333333  0.333333  0.00  

[5 rows x 2000 columns]

In [23]:
x_test = (x_test-x_test.min())/(x_test.max()-x_test.min())
x_test.head(5)

0     1         2         3     4     5     6     7     8     9     ...   \
0  0.00   0.0  0.000000  0.166667   0.0   0.5   0.0  0.00   0.0  0.00  ...    
1  0.00   0.0  0.333333  0.166667   0.0   0.5   0.0  0.00   0.0  0.50  ...    
2  0.75   0.2  0.000000  0.000000   0.0   0.5   0.0  0.00   0.0  0.00  ...    
3  0.00   0.4  0.333333  0.000000   0.0   0.0   0.0  0.25   0.0  0.00  ...    
4  0.00   0.0  0.000000  0.000000   0.0   0.0   0.0  0.00   0.0  0.75  ...    

   1990  1991      1992      1993  1994  1995  1996      1997      1998  1999  
0   0.5   0.0  0.000000  0.000000  0.00   0.4  0.00  0.000000  0.666667  0.25  
1   0.0   0.0  0.000000  0.333333  0.00   0.0  0.00  0.000000  0.000000  0.00  
2   0.0   0.0  0.000000  0.000000  0.00   0.0  0.00  0.000000  0.333333  0.00  
3   0.0   0.0  0.000000  0.000000  0.75   0.0  0.00  0.000000  0.000000  0.00  
4   0.0   0.0  0.333333  0.000000  0.00   0.0  0.25  0.333333  0.333333  0.00  

[5 rows x 2000 columns]

### Trainning

In [27]:
classifier = GaussianNB()
classifier.fit(x_train, y_train.values.ravel())

GaussianNB(priors=None, var_smoothing=1e-09)

In [28]:
y_pred = classifier.predict(x_test) 

In [29]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

1.0
[[56  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 24  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 16  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 25  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 30  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 23  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 29  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 16  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 16  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 16  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 16  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 10  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 11  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 16]]
