## import libraries

In [2]:
import pandas as pd
import numpy as np
from math import sqrt

### prepare data


In [20]:
df_train = pd.read_csv("data/faces/face_train.csv", delimiter=' ', header=None, names=[i for i in range(2049)], index_col=False)

In [21]:
df_test = pd.read_csv("data/faces/face_train.csv", delimiter=' ', header=None, names=[i for i in range(2049)], index_col=False)

### exploratory

In [22]:
df_train.head(10)

0         1         2         3         4         5         6     \
0  0.122055  0.367015  0.002846  0.453570  0.186527  0.165104  0.271614   
1  0.325929  0.473768  0.082610  0.360163  0.384997  0.316848  0.074394   
2  0.233870  0.678510  0.068670  0.297195  0.203807  0.291830  0.048955   
3  0.032220  0.552339  0.014047  0.375124  0.168801  0.054001  0.187133   
4  0.105044  0.490964  0.011058  0.474805  0.516650  0.356828  0.357900   
5  0.244331  0.295816  0.028140  0.414663  0.314368  0.498159  0.001929   
6  0.121096  0.499869  0.098142  0.363023  0.222358  0.334881  0.233069   
7  0.244841  0.651406  0.076367  0.380609  0.239624  0.274484  0.081328   
8  0.059435  1.028460  0.008268  0.257889  0.299861  0.160200  0.181218   
9  0.313819  0.715084  0.053784  0.087167  0.203280  0.624587  0.468400   

       7         8         9     ...       2039      2040      2041      2042  \
0  0.236254  0.285467  0.160386  ...   0.411760  0.466539  0.901325  0.520597   
1  0.195802  0.124269  0.437632  ...   0.193547  0.413448  1.030874  0.633866   
2  0.063495  0.248961  0.334037  ...   0.275544  0.421107  0.653588  0.310855   
3  0.050392  0.225371  0.176594  ...   0.166913  0.096000  1.010837  0.389454   
4  0.143014  0.164860  0.181786  ...   0.359511  0.060870  1.503733  0.285508   
5  0.240557  0.097844  0.593660  ...   0.095685  0.130606  0.971204  0.642408   
6  0.086880  0.354798  0.433899  ...   0.054846  0.472360  0.759462  0.221872   
7  0.125886  0.407403  0.470301  ...   0.143622  0.177599  0.916043  0.347380   
8  0.085647  0.208659  0.276492  ...   0.347504  0.453818  1.100169  0.084075   
9  0.166841  0.535240  0.200091  ...   0.036434  0.590954  1.502751  0.004601   

       2043      2044      2045      2046      2047  2048  
0  0.561105  0.219453  0.000000  0.063137  0.005620    18  
1  0.905277  0.067354  0.111569  0.138304  0.511756    17  
2  0.789908  0.008739  0.034649  0.151231  0.754876     2  
3  1.018565  0.142037  0.001631  0.000922  0.111003    16  
4  0.845285  0.307448  0.028159  0.103483  0.155505     7  
5  0.935789  0.126311  0.088386  0.140579  0.439417    17  
6  0.357876  0.006595  0.057398  0.073907  0.232972     8  
7  0.153477  0.039817  0.083686  0.075151  0.348655    13  
8  0.646029  0.113792  0.076908  0.204077  0.510680    19  
9  0.060697  0.032833  0.317756  0.000401  0.053126    15  

[10 rows x 2049 columns]

In [23]:
df_test.head(10)

0         1         2         3         4         5         6     \
0  0.122055  0.367015  0.002846  0.453570  0.186527  0.165104  0.271614   
1  0.325929  0.473768  0.082610  0.360163  0.384997  0.316848  0.074394   
2  0.233870  0.678510  0.068670  0.297195  0.203807  0.291830  0.048955   
3  0.032220  0.552339  0.014047  0.375124  0.168801  0.054001  0.187133   
4  0.105044  0.490964  0.011058  0.474805  0.516650  0.356828  0.357900   
5  0.244331  0.295816  0.028140  0.414663  0.314368  0.498159  0.001929   
6  0.121096  0.499869  0.098142  0.363023  0.222358  0.334881  0.233069   
7  0.244841  0.651406  0.076367  0.380609  0.239624  0.274484  0.081328   
8  0.059435  1.028460  0.008268  0.257889  0.299861  0.160200  0.181218   
9  0.313819  0.715084  0.053784  0.087167  0.203280  0.624587  0.468400   

       7         8         9     ...       2039      2040      2041      2042  \
0  0.236254  0.285467  0.160386  ...   0.411760  0.466539  0.901325  0.520597   
1  0.195802  0.124269  0.437632  ...   0.193547  0.413448  1.030874  0.633866   
2  0.063495  0.248961  0.334037  ...   0.275544  0.421107  0.653588  0.310855   
3  0.050392  0.225371  0.176594  ...   0.166913  0.096000  1.010837  0.389454   
4  0.143014  0.164860  0.181786  ...   0.359511  0.060870  1.503733  0.285508   
5  0.240557  0.097844  0.593660  ...   0.095685  0.130606  0.971204  0.642408   
6  0.086880  0.354798  0.433899  ...   0.054846  0.472360  0.759462  0.221872   
7  0.125886  0.407403  0.470301  ...   0.143622  0.177599  0.916043  0.347380   
8  0.085647  0.208659  0.276492  ...   0.347504  0.453818  1.100169  0.084075   
9  0.166841  0.535240  0.200091  ...   0.036434  0.590954  1.502751  0.004601   

       2043      2044      2045      2046      2047  2048  
0  0.561105  0.219453  0.000000  0.063137  0.005620    18  
1  0.905277  0.067354  0.111569  0.138304  0.511756    17  
2  0.789908  0.008739  0.034649  0.151231  0.754876     2  
3  1.018565  0.142037  0.001631  0.000922  0.111003    16  
4  0.845285  0.307448  0.028159  0.103483  0.155505     7  
5  0.935789  0.126311  0.088386  0.140579  0.439417    17  
6  0.357876  0.006595  0.057398  0.073907  0.232972     8  
7  0.153477  0.039817  0.083686  0.075151  0.348655    13  
8  0.646029  0.113792  0.076908  0.204077  0.510680    19  
9  0.060697  0.032833  0.317756  0.000401  0.053126    15  

[10 rows x 2049 columns]

### get features

In [7]:
x_train = df_train.iloc[:,:-1]
x_train.head(5)

0         1         2         3         4         5         6     \
0  0.122055  0.367015  0.002846  0.453570  0.186527  0.165104  0.271614   
1  0.325929  0.473768  0.082610  0.360163  0.384997  0.316848  0.074394   
2  0.233870  0.678510  0.068670  0.297195  0.203807  0.291830  0.048955   
3  0.032220  0.552339  0.014047  0.375124  0.168801  0.054001  0.187133   
4  0.105044  0.490964  0.011058  0.474805  0.516650  0.356828  0.357900   

       7         8         9       ...         2038      2039      2040  \
0  0.236254  0.285467  0.160386    ...     0.273536  0.411760  0.466539   
1  0.195802  0.124269  0.437632    ...     0.250488  0.193547  0.413448   
2  0.063495  0.248961  0.334037    ...     0.146017  0.275544  0.421107   
3  0.050392  0.225371  0.176594    ...     0.126632  0.166913  0.096000   
4  0.143014  0.164860  0.181786    ...     0.344958  0.359511  0.060870   

       2041      2042      2043      2044      2045      2046      2047  
0  0.901325  0.520597  0.561105  0.219453  0.000000  0.063137  0.005620  
1  1.030874  0.633866  0.905277  0.067354  0.111569  0.138304  0.511756  
2  0.653588  0.310855  0.789908  0.008739  0.034649  0.151231  0.754876  
3  1.010837  0.389454  1.018565  0.142037  0.001631  0.000922  0.111003  
4  1.503733  0.285508  0.845285  0.307448  0.028159  0.103483  0.155505  

[5 rows x 2048 columns]

In [8]:
x_test = df_test.iloc[:,:-1]
x_test.head(5)

0         1         2         3         4         5         6     \
0  0.122055  0.367015  0.002846  0.453570  0.186527  0.165104  0.271614   
1  0.325929  0.473768  0.082610  0.360163  0.384997  0.316848  0.074394   
2  0.233870  0.678510  0.068670  0.297195  0.203807  0.291830  0.048955   
3  0.032220  0.552339  0.014047  0.375124  0.168801  0.054001  0.187133   
4  0.105044  0.490964  0.011058  0.474805  0.516650  0.356828  0.357900   

       7         8         9       ...         2038      2039      2040  \
0  0.236254  0.285467  0.160386    ...     0.273536  0.411760  0.466539   
1  0.195802  0.124269  0.437632    ...     0.250488  0.193547  0.413448   
2  0.063495  0.248961  0.334037    ...     0.146017  0.275544  0.421107   
3  0.050392  0.225371  0.176594    ...     0.126632  0.166913  0.096000   
4  0.143014  0.164860  0.181786    ...     0.344958  0.359511  0.060870   

       2041      2042      2043      2044      2045      2046      2047  
0  0.901325  0.520597  0.561105  0.219453  0.000000  0.063137  0.005620  
1  1.030874  0.633866  0.905277  0.067354  0.111569  0.138304  0.511756  
2  0.653588  0.310855  0.789908  0.008739  0.034649  0.151231  0.754876  
3  1.010837  0.389454  1.018565  0.142037  0.001631  0.000922  0.111003  
4  1.503733  0.285508  0.845285  0.307448  0.028159  0.103483  0.155505  

[5 rows x 2048 columns]

### get labels

In [10]:
y_train = df_train.iloc[:,-1:]
y_train.head(5)

2048
0    18
1    17
2     2
3    16
4     7

In [27]:
y_trainset=y_train.values
y_trainset[:5]

array([[18],
       [17],
       [ 2],
       [16],
       [ 7]], dtype=int64)

In [28]:
y_test = df_test.iloc[:,-1:]
y_test.head(5)

2048
0    18
1    17
2     2
3    16
4     7

In [29]:
y_testset=y_test.values
y_testset[:5]

array([[18],
       [17],
       [ 2],
       [16],
       [ 7]], dtype=int64)

### data handling

In [30]:
x_trainset=x_train.values
x_trainset[:5]

array([[0.12205463, 0.36701545, 0.00284622, ..., 0.        , 0.06313663,
        0.00562035],
       [0.32592943, 0.47376841, 0.08261   , ..., 0.11156901, 0.13830385,
        0.51175606],
       [0.23387006, 0.67851049, 0.06867007, ..., 0.03464913, 0.15123141,
        0.75487602],
       [0.03222037, 0.55233914, 0.01404737, ..., 0.00163098, 0.00092247,
        0.11100324],
       [0.10504375, 0.49096441, 0.0110576 , ..., 0.0281592 , 0.10348342,
        0.15550488]])

In [31]:
x_testset=x_test.values
x_testset[:5]

array([[0.12205463, 0.36701545, 0.00284622, ..., 0.        , 0.06313663,
        0.00562035],
       [0.32592943, 0.47376841, 0.08261   , ..., 0.11156901, 0.13830385,
        0.51175606],
       [0.23387006, 0.67851049, 0.06867007, ..., 0.03464913, 0.15123141,
        0.75487602],
       [0.03222037, 0.55233914, 0.01404737, ..., 0.00163098, 0.00092247,
        0.11100324],
       [0.10504375, 0.49096441, 0.0110576 , ..., 0.0281592 , 0.10348342,
        0.15550488]])

In [32]:
y = []
for i in y_trainset:
    y.append(i[0])

In [34]:
trainset = np.insert(x_trainset, 2048, y, axis=1) 
trainset[:1]

array([[1.22054629e-01, 3.67015451e-01, 2.84621515e-03, ...,
        6.31366298e-02, 5.62035013e-03, 1.80000000e+01]])

In [35]:
yi = []
for i in y_testset:
    yi.append(i[0])

In [37]:
testset = np.insert(x_testset, 2048, yi , axis =1) 
testset[:5]

array([[1.22054629e-01, 3.67015451e-01, 2.84621515e-03, ...,
        6.31366298e-02, 5.62035013e-03, 1.80000000e+01],
       [3.25929433e-01, 4.73768413e-01, 8.26100037e-02, ...,
        1.38303846e-01, 5.11756063e-01, 1.70000000e+01],
       [2.33870059e-01, 6.78510487e-01, 6.86700717e-02, ...,
        1.51231408e-01, 7.54876018e-01, 2.00000000e+00],
       [3.22203711e-02, 5.52339137e-01, 1.40473694e-02, ...,
        9.22469539e-04, 1.11003242e-01, 1.60000000e+01],
       [1.05043747e-01, 4.90964413e-01, 1.10575985e-02, ...,
        1.03483416e-01, 1.55504882e-01, 7.00000000e+00]])

### Trainning

In [38]:
def Euclidean_distance(row1, row2):
    distance = 0
    for i in range(len(row1)-1):
        distance += (row1[i] - row2[i])**2
    return sqrt(distance)

"""
second function we have created is Get_Neighbors with the help of this function we can find out our nearest 3 datapoints.This function shows that the distance between our test data and training row is different.
"""

def Get_Neighbors(train, test_row, num):
   
    distance = list() # []
    data = []
    for i in train:
        dist = Euclidean_distance(test_row, i)
        distance.append(dist)
        data.append(i)
    distance = np.array(distance)
    data = np.array(data)

    """ we are finding index of min distance """

    index_dist = distance.argsort()

    """ we arange our data acco. to index """

    data  = data[index_dist]

    """ we are slicing num number of datas """

    neighbors = data[:num]
    
    return neighbors

"""Here we have created third function Predict_Classification for the prediction of values through our trained model"""  

def predict_classification(train, test_row, num):
    Neighbors = Get_Neighbors(train, test_row, num)
    Classes = []
    for i in Neighbors:
        Classes.append(i[-1])
    prediction = max(Classes, key= Classes.count)
    return prediction

"""We have created Evaluate Function for checking the accuracy of our predicted values """

def Evaluate(y_true, y_pred):
    n_correct = 0
    for i in range(len(y_true)):
        if y_true[i] == y_pred[i]:
            n_correct += 1

    acc = n_correct/len(y_true)
    
    return acc

In [39]:
prediction = predict_classification(trainset, testset[0], 1)

print("Label là:", prediction)

Label là: 18.0


### Evaluate

In [42]:
#created an empty list y_pred where we store all the prediction values.
y_pred = []
y_true = testset[:, -1]
for i in testset:
    prediction = predict_classification(trainset, i, 1)
    y_pred.append(prediction)

Evaluate(y_true, y_pred)

1.0

In [43]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_true, y_pred)

array([[56,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0, 46,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0, 49,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0, 39,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0, 28,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 27,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 21,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 25,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 71,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 45,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0