## import libraries

In [1]:
import pandas as pd
import numpy as np
from math import sqrt

### prepare data


In [2]:
df_train = pd.read_csv("data/fp/fp_train.csv",  header=None, names=[i for i in range(2001)], index_col=False)

In [3]:
df_test = pd.read_csv("data/fp/fp_test.csv", header=None, names=[i for i in range(2001)], index_col=False)

### exploratory

In [4]:
df_train.head(10)

0     1     2     3     4     5     6     7     8     9     ...   1991  \
0     0     0     0     1     0     1     0     0     0     0  ...      0   
1     0     0     1     1     0     1     0     0     0     2  ...      0   
2     3     1     0     0     0     1     0     0     0     0  ...      0   
3     0     2     1     0     0     0     0     1     0     0  ...      0   
4     0     0     0     0     0     0     0     0     0     3  ...      0   
5     0     0     0     0     0     0     0     0     0     0  ...      0   
6     0     0     0     1     0     1     0     0     0     0  ...      0   
7     0     0     0     0     0     0     2     0     0     2  ...      0   
8     0     1     0     0     0     1     0     0     0     0  ...      0   
9     0     0     0     0     0     1     0     0     0     0  ...      0   

   1992  1993  1994  1995  1996  1997  1998  1999  2000  
0     0     0     0     2     0     0     2     1     4  
1     0     2     0     0     0     0     0     0     7  
2     0     0     0     0     0     0     1     0    12  
3     0     0     3     0     0     0     0     0     5  
4     1     0     0     0     1     1     1     0     5  
5     0     0     0     0     0     0     0     0     9  
6     0     0     0     0     0     0     0     2     4  
7     0     0     0     0     0     1     1     0     1  
8     0     0     0     0     0     0     0     1    15  
9     0     0     0     0     0     0     0     0     8  

[10 rows x 2001 columns]

In [5]:
df_test.head(10)

0     1     2     3     4     5     6     7     8     9     ...   1991  \
0     0     1     0     0     0     1     0     1     0     0  ...      0   
1     0     1     4     0     2     1     0     0     0     0  ...      0   
2     0     0     0     0     0     0     1     0     5     1  ...      0   
3     0     0     1     0     2     1     0     0     0     0  ...      0   
4     1     0     1     0     0     0     2     0     0     1  ...      0   
5     0     1     0     0     0     1     0     0     0     0  ...      1   
6     2     0     0     0     0     0     0     0     0     0  ...      0   
7     0     0     1     0     0     1     0     0     0     0  ...      1   
8     0     1     0     0     0     1     0     0     0     1  ...      0   
9     2     0     0     0     0     0     1     0     0     0  ...      0   

   1992  1993  1994  1995  1996  1997  1998  1999  2000  
0     0     0     0     0     0     0     0     0    15  
1     0     0     0     0     0     0     1     0    11  
2     0     0     0     0     0     0     0     0     6  
3     0     0     0     0     0     0     3     0    10  
4     1     0     0     0     0     0     0     0     1  
5     0     0     0     0     0     0     1     0    12  
6     0     0     0     0     0     0     0     0     1  
7     0     0     0     0     0     0     1     0     8  
8     0     0     0     1     0     0     0     0     3  
9     0     0     0     0     0     0     0     0     1  

[10 rows x 2001 columns]

### get features

In [6]:
x_train = df_train.iloc[:,:-1]
x_train.head(5)

0     1     2     3     4     5     6     7     8     9     ...   1990  \
0     0     0     0     1     0     1     0     0     0     0  ...      2   
1     0     0     1     1     0     1     0     0     0     2  ...      0   
2     3     1     0     0     0     1     0     0     0     0  ...      0   
3     0     2     1     0     0     0     0     1     0     0  ...      0   
4     0     0     0     0     0     0     0     0     0     3  ...      0   

   1991  1992  1993  1994  1995  1996  1997  1998  1999  
0     0     0     0     0     2     0     0     2     1  
1     0     0     2     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     1     0  
3     0     0     0     3     0     0     0     0     0  
4     0     1     0     0     0     1     1     1     0  

[5 rows x 2000 columns]

In [7]:
x_test = df_test.iloc[:,:-1]
x_test.head(5)

0     1     2     3     4     5     6     7     8     9     ...   1990  \
0     0     1     0     0     0     1     0     1     0     0  ...      0   
1     0     1     4     0     2     1     0     0     0     0  ...      0   
2     0     0     0     0     0     0     1     0     5     1  ...      1   
3     0     0     1     0     2     1     0     0     0     0  ...      0   
4     1     0     1     0     0     0     2     0     0     1  ...      0   

   1991  1992  1993  1994  1995  1996  1997  1998  1999  
0     0     0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0     1     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0     3     0  
4     0     1     0     0     0     0     0     0     0  

[5 rows x 2000 columns]

### get labels

In [8]:
y_train = df_train.iloc[:,-1:]
y_train.head(5)

2000
0     4
1     7
2    12
3     5
4     5

In [9]:
y_trainset=y_train.values
y_trainset[:5]

array([[ 4],
       [ 7],
       [12],
       [ 5],
       [ 5]], dtype=int64)

In [10]:
y_test = df_test.iloc[:,-1:]
y_test.head(5)

2000
0    15
1    11
2     6
3    10
4     1

In [12]:
y_testset=y_test.values
y_testset[:5]

array([[15],
       [11],
       [ 6],
       [10],
       [ 1]], dtype=int64)

### data normalization

In [19]:
x_train = (x_train-x_train.min())/(x_train.max()-x_train.min())
x_train.head(5)

0     1         2         3     4     5     6     7     8     9     ...   \
0  0.00   0.0  0.000000  0.166667   0.0   0.5   0.0  0.00   0.0  0.00  ...    
1  0.00   0.0  0.333333  0.166667   0.0   0.5   0.0  0.00   0.0  0.50  ...    
2  0.75   0.2  0.000000  0.000000   0.0   0.5   0.0  0.00   0.0  0.00  ...    
3  0.00   0.4  0.333333  0.000000   0.0   0.0   0.0  0.25   0.0  0.00  ...    
4  0.00   0.0  0.000000  0.000000   0.0   0.0   0.0  0.00   0.0  0.75  ...    

   1990  1991      1992      1993  1994  1995  1996      1997      1998  1999  
0   0.5   0.0  0.000000  0.000000  0.00   0.4  0.00  0.000000  0.666667  0.25  
1   0.0   0.0  0.000000  0.333333  0.00   0.0  0.00  0.000000  0.000000  0.00  
2   0.0   0.0  0.000000  0.000000  0.00   0.0  0.00  0.000000  0.333333  0.00  
3   0.0   0.0  0.000000  0.000000  0.75   0.0  0.00  0.000000  0.000000  0.00  
4   0.0   0.0  0.333333  0.000000  0.00   0.0  0.25  0.333333  0.333333  0.00  

[5 rows x 2000 columns]

In [24]:
x_trainset=x_train.values
x_trainset[:5]

array([[0.        , 0.        , 0.        , ..., 0.        , 0.66666667,
        0.25      ],
       [0.        , 0.        , 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.75      , 0.2       , 0.        , ..., 0.        , 0.33333333,
        0.        ],
       [0.        , 0.4       , 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.33333333, 0.33333333,
        0.        ]])

In [23]:
x_test = (x_test-x_test.min())/(x_test.max()-x_test.min())
x_test.head()

0         1     2     3     4     5         6         7      8     \
0  0.000000  0.333333   0.0   0.0   0.0   1.0  0.000000  0.333333  0.000   
1  0.000000  0.333333   0.8   0.0   1.0   1.0  0.000000  0.000000  0.000   
2  0.000000  0.000000   0.0   0.0   0.0   0.0  0.333333  0.000000  0.625   
3  0.000000  0.000000   0.2   0.0   1.0   1.0  0.000000  0.000000  0.000   
4  0.333333  0.000000   0.2   0.0   0.0   0.0  0.666667  0.000000  0.000   

   9     ...       1990  1991      1992  1993  1994  1995  1996  1997  \
0   0.0  ...   0.000000   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   
1   0.0  ...   0.000000   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   
2   0.2  ...   0.333333   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   
3   0.0  ...   0.000000   0.0  0.000000   0.0   0.0   0.0   0.0   0.0   
4   0.2  ...   0.000000   0.0  0.333333   0.0   0.0   0.0   0.0   0.0   

       1998  1999  
0  0.000000   0.0  
1  0.333333   0.0  
2  0.000000   0.0  
3  1.000000   0.0  
4  0.000000   0.0  

[5 rows x 2000 columns]

In [25]:
x_testset=x_test.values
x_testset[:5]

array([[0.        , 0.33333333, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.33333333, 0.8       , ..., 0.        , 0.33333333,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.2       , ..., 0.        , 1.        ,
        0.        ],
       [0.33333333, 0.        , 0.2       , ..., 0.        , 0.        ,
        0.        ]])

### data handling

In [26]:
y = []
for i in y_trainset:
    y.append(i[0])

In [27]:
trainset = np.insert(x_trainset, 2000, y, axis=1) 
trainset[:5]

array([[ 0.        ,  0.        ,  0.        , ...,  0.66666667,
         0.25      ,  4.        ],
       [ 0.        ,  0.        ,  0.33333333, ...,  0.        ,
         0.        ,  7.        ],
       [ 0.75      ,  0.2       ,  0.        , ...,  0.33333333,
         0.        , 12.        ],
       [ 0.        ,  0.4       ,  0.33333333, ...,  0.        ,
         0.        ,  5.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.33333333,
         0.        ,  5.        ]])

In [28]:
yi = []
for i in y_testset:
    yi.append(i[0])

In [30]:
testset = np.insert(x_testset, 2000, yi , axis =1) 
testset[:5]

array([[ 0.        ,  0.33333333,  0.        , ...,  0.        ,
         0.        , 15.        ],
       [ 0.        ,  0.33333333,  0.8       , ...,  0.33333333,
         0.        , 11.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  6.        ],
       [ 0.        ,  0.        ,  0.2       , ...,  1.        ,
         0.        , 10.        ],
       [ 0.33333333,  0.        ,  0.2       , ...,  0.        ,
         0.        ,  1.        ]])

### Trainning

In [31]:
def Euclidean_distance(row1, row2):
    distance = 0
    for i in range(len(row1)-1):
        distance += (row1[i] - row2[i])**2
    return sqrt(distance)

"""
second function we have created is Get_Neighbors with the help of this function we can find out our nearest 3 datapoints.This function shows that the distance between our test data and training row is different.
"""

def Get_Neighbors(train, test_row, num):
   
    distance = list() # []
    data = []
    for i in train:
        dist = Euclidean_distance(test_row, i)
        distance.append(dist)
        data.append(i)
    distance = np.array(distance)
    data = np.array(data)

    """ we are finding index of min distance """

    index_dist = distance.argsort()

    """ we arange our data acco. to index """

    data  = data[index_dist]

    """ we are slicing num number of datas """

    neighbors = data[:num]
    
    return neighbors

"""Here we have created third function Predict_Classification for the prediction of values through our trained model"""  

def predict_classification(train, test_row, num):
    Neighbors = Get_Neighbors(train, test_row, num)
    Classes = []
    for i in Neighbors:
        Classes.append(i[-1])
    prediction = max(Classes, key= Classes.count)
    return prediction

"""We have created Evaluate Function for checking the accuracy of our predicted values """

def Evaluate(y_true, y_pred):
    n_correct = 0
    for i in range(len(y_true)):
        if y_true[i] == y_pred[i]:
            n_correct += 1

    acc = n_correct/len(y_true)
    
    return acc

In [32]:
prediction = predict_classification(trainset, testset[0], 1)

print("Label là:", prediction)

Label là: 15.0


### Evaluate

In [35]:
#created an empty list y_pred where we store all the prediction values.
y_pred = []
y_true = testset[:, -1]
for i in testset:
    prediction = predict_classification(trainset, i, 1)
    y_pred.append(prediction)

Evaluate(y_true, y_pred)

0.96875

In [34]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_true, y_pred)

array([[29,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  0,  0,  0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  9,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  1,  0,  8,  0],
       [ 0,  0,  0,  0,  0,  0,  0